---
title: "MMS Project Pieces: Data Exploration and Visualization"
author: "Samantha Piatt"
date: April 4, 2018
output: pdf_document
---
```{r page_options, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, fig.asp = 0.88, fig.width = 4)

library(MASS)
library(ggplot2)
library(splines)
library(magrittr)

source("GetDataFunctions.R")
source("ExperimentalFunctions.R")
```
```{r, import_dataBuild}
data <- merge_sitl("mms_20151016.csv", "sitl_20151016.csv")
data$SelectedF <- as.factor(data$Selected)

DES_set <- c("DES_Density", "DES_Temperature_para", "DES_Temperature_perp", "DES_Velocity_x", 
             "DES_Velocity_y", "DES_Velocity_z")
DIS_set <- c("DIS_Density", "DIS_Temperature_para", "DIS_Temperature_perp", "DIS_Velocity_x",
             "DIS_Velocity_y", "DIS_Velocity_z")
FGM_set <- c("FGM_Magnetic_Field_w", "FGM_Magnetic_Field_x", "FGM_Magnetic_Field_y",
             "FGM_Magnetic_Field_z")
SEL_set <- c("Time", "Selected")
featureSubset <- c(DES_set, DIS_set, FGM_set)
```

# Data Exploration and Visualization
Here is a visualization of dataset 1.
```{r dataEx_data_plot, fig.width = 12, fig.asp = 0.75, fig.align = "center"}
DES <- reshape::melt(data.frame(data[, DES_set], Time = data$Time), id = 'Time')
DIS <- reshape::melt(data.frame(data[, DIS_set], Time = data$Time), id = 'Time')
FGM <- reshape::melt(data.frame(data[, FGM_set], Time = data$Time), id = 'Time')
SEL <- data.frame(X = data$Time, Y = data$Selected)
free = 50

remove_axis <- theme(axis.title.x=element_blank(), axis.text.x=element_blank(), axis.line.x = element_blank())
remove_legend <- theme(legend.position='none')
theme_set(theme_grey() + theme(legend.justification = "left", plot.margin = margin(0, 0, 0, 0)))

spDES <- ggplot(DES, aes(x = Time, y = value, color = variable)) + geom_smooth(method = "lm", formula = y ~ ns(x, df = free), se = FALSE) + remove_axis +
  ylab("DES") + guides(color = guide_legend(title = "DES")) + labs(title = "Features Grouped by Instrument and Time")
spDIS <- ggplot(DIS, aes(x = Time, y = value, color = variable)) + geom_smooth(method = "lm", formula = y ~ ns(x, df = free), se = FALSE) + remove_axis +
  ylab("DIS") + guides(color = guide_legend(title = "DIS")) + theme(plot.title = element_blank())
spFGM <- ggplot(FGM, aes(x = Time, y = value, color = variable)) + geom_smooth(method = "lm", formula = y ~ ns(x, df = free), se = FALSE) + remove_axis +
  ylab("FGM") + guides(color = guide_legend(title = "FGM"))
pSEL <- ggplot(SEL, aes(x = X, y = Y)) + geom_line() + xlab("Time in Seconds")+ scale_y_discrete(name = "Selected", limits = c(0, 1))

lDES <- cowplot::get_legend(spDES)
lDIS <- cowplot::get_legend(spDIS)
lFGM <- cowplot::get_legend(spFGM)

cowplot::plot_grid(
  cowplot::plot_grid(spDES + remove_legend, spDIS + remove_legend, spFGM + remove_legend, pSEL, align = "hv", ncol = 1, rel_heights = c(1, 1, 1, 0.4)),
  cowplot::plot_grid(lDES, lDIS, lFGM, NULL, ncol = 1, rel_heights = c(1, 1, 1, 0.4)),
  rel_widths = c(5, 1)
)
```


```{r dataEx_relationship_plots, fig.width = 8, fig.asp = 1.5, fig.align = "center"}
cowplot::plot_grid(
  ggplot(data.frame(Para = data$DES_Temperature_para, Perp = data$DES_Temperature_perp), aes(x = Para, y = Perp)) + 
    geom_point(colour = "#591d91", shape = 1) + theme_grey() + labs(title = "DES Temperature"),
  ggplot(data.frame(Y = data$FGM_Magnetic_Field_y, Z = data$FGM_Magnetic_Field_z), aes(x = Y, y = Z, color = "#8f8699")) + 
    geom_point(colour = "#591d91", shape = 1) + theme_grey() + labs(title = "FGM Magnetic Field"),
  ggplot(data.frame(Density = data$DES_Density, Velocity = data$DES_Velocity_x), aes(y = Density, x = Velocity)) + 
    geom_point(colour = "#591d91", shape = 1) + theme_grey() +
    labs(title = "DES Density & Velocity X"),
  ggplot(data.frame(Density = data$DES_Density, Perp = data$DES_Temperature_perp), aes(y = Density, x = Perp, color = "#8f8699")) + 
    geom_point(colour = "#591d91", shape = 1) + theme_grey() +
    labs(title = "DES Density and FGM Magnetic Field"),
  ggplot(data.frame(Density = data$DES_Density, Perp = ( 1 / data$DES_Temperature_perp )), aes(y = Density, x = Perp, color = "#8f8699")) + 
    geom_point(colour = "#591d91", shape = 1) + theme_grey() +
    labs(title = "DES Density and FGM Magnetic Field") + xlab("1 / Perp"),
  ggplot(data.frame(w = data$FGM_Magnetic_Field_w, z = data$FGM_Magnetic_Field_z), aes(y = w, x = z, color = "#8f8699")) + 
    geom_point(colour = "#591d91", shape = 1) + theme_grey() +
    labs(title = "FGM Magnetic Field"),
  ncol = 2
)
```

## Time Series Exploration
```{r ts_base_loglasso}
train <- split_train(data, seed = 100)
test <- split_test(data, seed = 100)
line <- "\n--------------------------------------\n"

log.lasso.fit <- glmnetUtils::cv.glmnet(Selected ~ . - Time - Priority - SelectedF, data = train, family = "binomial")
log.odds <- predict(log.lasso.fit, data)
probabilities <- exp(log.odds) / (1 + exp(log.odds))
cat("Basic Logistic Lasso Total Error", line)
evaluate_data(data, probabilities)
```

```{r ts_base_SVM}
rsvm.fit <- e1071::svm(SelectedF ~ . - Time - Priority - Selected, data = train, 
                       kernel = "radial", probability = TRUE, cross = 10)

cat("Basic SVM Error\n")
cat("Total Accuracy via CV: ", rsvm.fit$tot.accuracy, "\n\n")

rsvm.pred <- predict(rsvm.fit, train, probability = TRUE)
rsvm.pred <- attr(rsvm.pred, "probabilities")[,2]
cat("Train data", line)
evaluate_data(train, rsvm.pred)

rsvm.pred <- predict(rsvm.fit, test, probability = TRUE)
rsvm.pred <- attr(rsvm.pred, "probabilities")[,2]
cat("Test data", line)
evaluate_data(test, rsvm.pred)

rsvm.pred <- predict(rsvm.fit, data, probability = TRUE)
rsvm.pred <- attr(rsvm.pred, "probabilities")[,2]
cat("Total", line)
evaluate_data(data, rsvm.pred)
```


```{r ts_series_dataBuild}
diffData <- data.frame(X = data$X, series_metric(data[,featureSubset], 20), data[, SEL_set], Priority = data$Priority, SelectedF = data$SelectedF)
diffTrain <- split_train(diffData, seed = 100)
diffTest <- split_test(diffData, seed = 100)
```
```{r ts_series_loglasso}
log.lasso.fit <- glmnetUtils::cv.glmnet(Selected ~ . - Time - Priority - SelectedF, data = diffTrain, family = "binomial")
log.odds <- predict(log.lasso.fit, diffData)
probabilities <- exp(log.odds) / (1 + exp(log.odds))
cat("Time Series Logistic Lasso Total Error", line)
evaluate_data(diffData, probabilities)
save_predictions(probabilities, diffData$X, "Base_LogLasso.csv")
```

```{r ts_series_SVM}
rsvm.fit <- e1071::svm(SelectedF ~ . - Time - Priority - Selected, data = diffTrain, 
                       kernel = "radial", probability = TRUE, cross = 10)

cat("Time Series SVM Error\n")
cat("Total Accuracy via CV: ", rsvm.fit$tot.accuracy, "\n\n")

rsvm.pred <- predict(rsvm.fit, diffTrain, probability = TRUE)
rsvm.pred <- attr(rsvm.pred, "probabilities")[,2]
cat("Train data", line)
evaluate_data(diffTrain, rsvm.pred)

rsvm.pred <- predict(rsvm.fit, diffTest, probability = TRUE)
rsvm.pred <- attr(rsvm.pred, "probabilities")[,2]
cat("Test data", line)
evaluate_data(diffTest, rsvm.pred)

rsvm.pred <- predict(rsvm.fit, diffData, probability = TRUE)
rsvm.pred <- attr(rsvm.pred, "probabilities")[,2]
cat("Total", line)
evaluate_data(diffData, rsvm.pred)

save_predictions(rsvm.pred, data$X, "TS_RSVM.csv")
```
